# Generated by Django 3.2 on 2022-07-03 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('text_content', models.TextField()),
                ('image_one', models.ImageField(blank=True, default='placeholder_one', null=True, upload_to='')),
                ('image_two', models.ImageField(blank=True, default='placeholder_two', null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
