# Generated by Django 3.2 on 2022-07-28 09:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_battles', '0002_auto_20220704_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_one',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder_one', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_two',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder_two', max_length=255, null=True),
        ),
    ]
