# Generated by Django 3.2 on 2022-07-30 11:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_battles', '0003_auto_20220728_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_one',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_two',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
