# Generated by Django 3.2 on 2022-07-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StandardProduct',
            new_name='CustomProduct',
        ),
    ]
