# Generated by Django 3.2 on 2022-07-13 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_products', '0002_rename_standardproduct_customproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='brim_width',
            field=models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='hat_height',
            field=models.IntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(35)]),
        ),
    ]
