# Generated by Django 3.2 on 2022-07-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_products', '0003_auto_20220713_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='color',
            field=models.CharField(choices=[('PURPLE', 'Purple'), ('NAVY', 'Navy'), ('PINK', 'Pink'), ('GREEN', 'Green'), ('ORANGE', 'Orange')], default='PURPLE', max_length=254),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='patch',
            field=models.CharField(blank=True, choices=[('STAR', 'Star'), ('MOON', 'Crescent moon'), ('PRIDE', 'Pride flag'), ('TRANS', 'Trans flag'), ('ANARCHY', 'Anarchy patch')], default='STAR', max_length=254, null=True),
        ),
    ]
