# Generated by Django 3.2 on 2022-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_products', '0004_auto_20220713_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='patch',
            field=models.CharField(blank=True, choices=[('STAR', 'Star'), ('MOON', 'Crescent moon'), ('PRIDE', 'Pride flag'), ('TRANS', 'Trans flag'), ('ANARCHY', 'Anarchy patch'), ('NONE', 'None')], default='STAR', max_length=254, null=True),
        ),
    ]
