# Generated by Django 3.2 on 2022-07-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_products', '0005_alter_customproduct_patch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomProduct',
        ),
    ]
