# Generated by Django 3.2 on 2022-07-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfilled',
            field=models.BooleanField(),
        ),
    ]
