# Generated by Django 3.2 on 2022-07-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard_products', '0002_auto_20220709_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardproduct',
            name='stat_category_one',
        ),
        migrations.RemoveField(
            model_name='standardproduct',
            name='stat_category_two',
        ),
        migrations.RemoveField(
            model_name='standardproduct',
            name='stat_number_one',
        ),
        migrations.RemoveField(
            model_name='standardproduct',
            name='stat_number_two',
        ),
    ]
