# Generated by Django 3.2 on 2022-07-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard_products', '0003_auto_20220709_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardproduct',
            name='stat',
        ),
        migrations.AddField(
            model_name='standardproduct',
            name='stat_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stat_one', to='standard_products.stat'),
        ),
        migrations.AddField(
            model_name='standardproduct',
            name='stat_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stat_two', to='standard_products.stat'),
        ),
    ]
