# Generated by Django 3.2 on 2022-07-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_products', '0005_auto_20220709_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardproduct',
            name='stock_level',
            field=models.IntegerField(default=1),
        ),
    ]
