# Generated by Django 3.2 on 2022-07-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_products', '0006_alter_standardproduct_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardproduct',
            name='img_alt_text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
