# Generated by Django 3.2 on 2022-07-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard_products', '0007_standardproduct_img_alt_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardproduct',
            old_name='img_alt_text',
            new_name='image_alt_text',
        ),
    ]
