# Generated by Django 3.2 on 2022-07-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_products', '0008_rename_img_alt_text_standardproduct_image_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('stat', models.CharField(blank=True, max_length=254, null=True)),
                ('price', models.IntegerField()),
                ('color', models.CharField(choices=[('PURPLE', 'Purple'), ('NAVY', 'Navy'), ('PINK', 'Pink'), ('GREEN', 'Green'), ('ORANGE', 'Orange')], default='PURPLE', max_length=20)),
                ('variable_one', models.CharField(blank=True, max_length=254, null=True)),
                ('variable_two', models.CharField(blank=True, max_length=254, null=True)),
                ('variable_three', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StandardProduct',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
