# Generated by Django 3.2 on 2022-07-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_products', '0009_auto_20220715_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stat',
            field=models.CharField(choices=[('PURPLE', 'Purple'), ('NAVY', 'Navy'), ('PINK', 'Pink'), ('GREEN', 'Green'), ('ORANGE', 'Orange')], default='COURAGE', max_length=50),
        ),
    ]
