# Generated by Django 3.2 on 2022-07-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_products', '0010_alter_product_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stat',
            field=models.CharField(choices=[('COURAGE', 'Courage'), ('COOL', 'Cool'), ('SUN_PROTECTION', 'Sun Protection'), ('SPELL_CASTING', 'Spell Casting'), ('STEALTH', 'Stealth')], default='COURAGE', max_length=50),
        ),
    ]
