# Generated by Django 3.2 on 2022-07-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='variable_one',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variable_three',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variable_two',
        ),
        migrations.AlterField(
            model_name='product',
            name='stat',
            field=models.CharField(choices=[('Courage', 'Courage'), ('Cool', 'Cool'), ('Sun Protection', 'Sun Protection'), ('Spell Casting', 'Spell Casting'), ('Stealth', 'Stealth')], default='COURAGE', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomisationOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_one', to='products.customisation')),
                ('variable_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_three', to='products.customisation')),
                ('variable_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_two', to='products.customisation')),
            ],
        ),
    ]
