# Generated by Django 3.2 on 2022-07-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220721_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisation',
            name='assoc_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product'),
        ),
    ]
