# Generated by Django 3.2 on 2022-07-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_customisation_assoc_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customisationoptions',
            name='variable_three',
        ),
        migrations.RemoveField(
            model_name='customisationoptions',
            name='variable_two',
        ),
        migrations.AddField(
            model_name='customisationoptions',
            name='option_one',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customisationoptions',
            name='option_three',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customisationoptions',
            name='option_two',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
