# Generated by Django 3.2 on 2022-07-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220721_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customisationoptions',
            old_name='variable_one',
            new_name='variable',
        ),
    ]
