# Generated by Django 3.2 on 2022-07-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customisationoptions',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='products.customisation'),
        ),
    ]
