# Generated by Django 3.2 on 2022-07-24 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_alter_customisationoptions_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, max_length=50, null=True)),
                ('stat', models.BooleanField()),
                ('color', models.BooleanField()),
                ('variable_one', models.CharField(blank=True, max_length=50, null=True)),
                ('variable_one_option_one', models.CharField(blank=True, max_length=254, null=True)),
                ('variable_one_option_two', models.CharField(blank=True, max_length=254, null=True)),
                ('variable_one_option_three', models.CharField(blank=True, max_length=254, null=True)),
                ('variable_two', models.CharField(blank=True, max_length=50, null=True)),
                ('variable_two_option_one', models.CharField(blank=True, max_length=254, null=True)),
                ('variable_two_option_two', models.CharField(blank=True, max_length=254, null=True)),
                ('variable_two_option_three', models.CharField(blank=True, max_length=254, null=True)),
                ('variable_three', models.CharField(blank=True, max_length=50, null=True)),
                ('variable_three_option_one', models.CharField(blank=True, max_length=254, null=True)),
                ('variable_three_option_two', models.CharField(blank=True, max_length=254, null=True)),
                ('variable_three_option_three', models.CharField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='customisationoptions',
            name='variable',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='variable_one',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='variable_three',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='variable_two',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Customisation',
        ),
        migrations.DeleteModel(
            name='CustomisationOptions',
        ),
    ]
