# Generated by Django 3.2 on 2022-07-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220724_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsubmission',
            name='color',
            field=models.BooleanField(verbose_name='Include colors'),
        ),
        migrations.AlterField(
            model_name='staffsubmission',
            name='stat',
            field=models.BooleanField(verbose_name='Include stats'),
        ),
    ]
